version: '3.9'

services:
  postgres:
    container_name: blogging_techorda_container
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "bloggingdb"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: